const DIAGNOSTICOS = {
  "A+_B-_C-": `O MELHOR CENÁRIO POSSÍVEL:
TRABALHO DE MANUTENÇÃO E REVISÃO ESPAÇADA DOS CONTEÚDOS
REVISÃO ESPAÇADA: ENTRE 1 MÊS E 15 DIAS DE REVISÃO DO CONTEÚDO`,

  "A+_B+/-_C-": `ABAIXO DO MELHOR CENÁRIO:
MANUTENÇÃO DOS A´s E FOCO EM ENTENDER OS B´s (APOSTILA OU VIDEOAULA)`,

  "A+_B+_C-": `CENÁRIO ANIMADOR:
FOCO EM DIMINUIR O NÚMERO DE B´s (APOSTILA OU VIDEOAULA)`,

  "A+_B-_C+/-": `MELHOR:
FOCO EM IGUALAR C´s COM B´s (APOSTILA OU VIDEOAULA) E SÓ DEPOIS DISSO FOCAR NOS B´s`,

  "A+_B+/-_C+/-": `MELHORANDO:
FOCO EM COLOCAR OS C´s NOS B´s (COMEÇAR A ENTENDER O QUE NÃO SEI: ESTUDE POR APOSTILA) –
OU SEJA, DIMINUIR C´s AUMENTA OS B´s PARA DEPOIS AUMENTAR OS A´s`,

  "A+_B+_C+/-": `BOM:
PEGUE OS B´s ESTUDE E FAÇA EXERCÍCIOS (ENTENDENDO-OS, FARÁ SEUS C´s DIMINUIREM)`,

  "A+_B-_C+": `PERTO DE BOM:
FOCAR EM DIMINUIR C´s (VEJA VÍDEOAULAS DOS ASSUNTOS) – PASSE A CONHECER O QUE NÃO SABE NADA`,

  "A+_B+/-_C+": `MAIS ACIMA DA MÉDIA:
ESTUDAR B´s E C´s (VIDEOAULA E EXERCÍCIOS DE FORMA REPETITIVA)
DE 1 SEMANA A 15 DIAS REVENDO CONTEÚDOS`,

  "A+_B+_C+": `ACIMA DA MÉDIA:
ESTUDAR B´s E C´s (VIDEOAULA E EXERCÍCIOS DE FORMA MUITO REPETITIVA)
DE 1 SEMANA A 10 DIAS REVENDO CONTEÚDOS`,

  "A+/-_B-_C-": `NA MÉDIA:
FOCO EM AUMENTAR O NÚMERO DE A´s (APOSTILA + EXERCÍCIOS)
VOCÊ PRECISA APRENDER MAIS (MAIS FOCO E REPETIÇÃO)`,

  "A+/-_B+/-_C-": `UM POUCO ABAIXO DA MÉDIA:
FOCO EM AUMENTAR A´s E B´s (APOSTILA + EXERCÍCIOS)
VOCÊ PRECISA APRENDER MAIS (MAIS FOCO E REPETIÇÃO)`,

  "A+/-_B+_C-": `MEDÍOCRE:
FOCAR EM DIMINUIR B´s (ISSO FAZ SEUS A´s AUMENTAREM: APOSTILA + EXERCÍCIOS)
DE 1 SEMANA A 15 DIAS REVENDO CONTEÚDOS`,

  "A+/-_B-_C+/-": `REGULAR:
ESTUDAR OS C´s E INICIAR O PROCESSO DE ENTENDÊ-LOS (APOSTILA + EXERCÍCIOS)
DE 1 SEMANA A 15 DIAS REVENDO CONTEÚDOS`,

  "A+/-_B+/-_C+/-": `ABAIXO DE REGULAR:
ESTUDAR OS B´s E C´s (VIDEOAULA + EXERCÍCIOS)
DE 1 SEMANA A 15 DIAS REVENDO CONTEÚDOS`,

  "A+/-_B+_C+/-": `ZONA DE INSEGURANÇA:
DIMINUIR C´s E TRANSFORMAR B´s EM A´s (VIDEOAULA + EXERCÍCIOS)
DE 1 SEMANA A 10 DIAS REVENDO CONTEÚDOS`,

  "A+/-_B-_C+": `INSEGURANÇA:
FOCO EM DIMINUIR C´s (VIDEOAULA + EXERCÍCIOS)
DE 1 SEMANA A 10 DIAS REVENDO CONTEÚDOS`,

  "A+/-_B+/-_C+": `NO LIMITE:
FOCO EM DIMINUIR C´s E ESTUDAR BEM OS B´s (VIDEOAULA + EXERCÍCIOS)
DE 1 SEMANA A 10 DIAS REVENDO CONTEÚDOS`,

  "A+/-_B+_C+": `LIMITE PERIGOSO:
FOCO EM DIMINUIR B´s E C´s (VIDEOAULA + EXERCÍCIOS)
DE 1 SEMANA A 10 DIAS REVENDO CONTEÚDOS`,

  "A-_B-_C-": `ZONA DE ALERTA:
REESTUDAR TODOS OS ASSUNTOS COM VIDEOAULA OU APOSTILA
DE FORMA MUITO REPETITIVA POR 1 A 10 DIAS`,

  "A-_B+/-_C-": `RUIM:
É PRECISO PROCURAR UM CURSINHO PRÉ-VESTIBULAR DE NÍVEL MÉDIO
(ALÉM DE ESTUDAR EM CASA)`,

  "A-_B+_C-": `BEM RUIM:
É PRECISO PROCURAR UM CURSINHO PRÉ-VESTIBULAR DE NÍVEL FORTE
(ALÉM DE ESTUDAR EM CASA)`,

  "A-_B-_C+/-": `MUITO RUIM:
CURSINHO DE NÍVEL FORTE + PROGRAMAS DE ESTUDOS COMPLEMENTARES
(ESTUDAR EM CASA)`,

  "A-_B+/-_C+/-": `PÉSSIMO:
CURSINHO PREPARATÓRIO PARA O ENSINO MÉDIO + ROTINA INTENSA DE ESTUDOS`,

  "A-_B+_C+/-": `RESULTADO HORRÍVEL:
CURSINHO PARA ENSINO MÉDIO, ROTINA INTENSA DE ESTUDOS E MUITO EXERCÍCIO BÁSICO (ALÉM DE ESTUDAR EM CASA)`,

  "A-_B-_C+": `PRÓXIMO DO TRÁGICO:
RECOMEÇAR O ENSINO MÉDIO: VIDEOAULAS + ANOTAÇÕES + EXERCÍCIOS`,

  "A-_B+/-_C+": `TRAGÉDIA:
REFORÇO ESCOLAR MÉDIO COM REVISÃO DO FUNDAMENTAL II E MÉDIO`,

  "A-_B+_C+": `ABAIXO DA TRAGÉDIA:
REVER FUNDAMENTAL II + CORRIGIR LACUNAS BÁSICAS (REFORÇO FORTE)`
};

export function getDiagnostico(classA, classB, classC) {
  return DIAGNOSTICOS[`${classA}_${classB}_${classC}`];
}